import keyboard
import time

def execPatch():
    keyboard.send('`')
    keyboard.send('e')
    keyboard.send('x')
    keyboard.send('e')
    keyboard.send('c')
    keyboard.send('space')
    keyboard.send('p')
    keyboard.send('a')
    keyboard.send('t')
    keyboard.send('c')
    keyboard.send('h')
    keyboard.send('.')
    keyboard.send('t')
    keyboard.send('x')
    keyboard.send('t')
    keyboard.send('enter')
    keyboard.send('`')

def colorblindFix():
    keyboard.send('escape')
    time.sleep(.02)
    keyboard.send('down'); keyboard.send('down')
    keyboard.send('enter')
    time.sleep(.035)
    keyboard.send('down'); keyboard.send('down')
    keyboard.send('enter')
    time.sleep(.02)
    keyboard.send('down'); keyboard.send('down'); keyboard.send('down'); keyboard.send('down')
    keyboard.send('down'); keyboard.send('down'); keyboard.send('down'); keyboard.send('down')
    keyboard.send('down'); keyboard.send('down'); keyboard.send('down'); keyboard.send('down')
    keyboard.send('down'); keyboard.send('down'); keyboard.send('down'); keyboard.send('down')
    keyboard.send('down'); keyboard.send('down'); keyboard.send('down'); keyboard.send('down')
    keyboard.send('down')
    keyboard.send('right'); keyboard.send('right')
    time.sleep(.05)
    keyboard.send('escape'); keyboard.send('escape'); keyboard.send('escape')

def reload():
    keyboard.send('escape')
    time.sleep(.02)
    keyboard.send('down'); keyboard.send('down'); keyboard.send('down'); keyboard.send('down')
    keyboard.send('enter')
    time.sleep(.05)
    keyboard.send('up')
    keyboard.send('enter')
    time.sleep(2)
    keyboard.send('enter')
    time.sleep(.05)
    keyboard.send('enter')

'''
def readOnlyReload():
    keyboard.send('escape')
    time.sleep(.02)
    keyboard.send('down'); keyboard.send('down'); keyboard.send('down'); keyboard.send('down')
    keyboard.send('enter')
    time.sleep(.05)
    keyboard.send('up')
    keyboard.send('enter')
    time.sleep(1.8)
    keyboard.send('down'); keyboard.send('down'); keyboard.send('down'); keyboard.send('down')
'''